syntax on
set number
set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
set showmatch
set cursorline
set incsearch
set smarttab

"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/Users/rikiyak/.vim/dein/repos/github.com/Shougo/dein.vim

" Required:
call dein#begin('/Users/rikiyak/.vim/dein')

" Let dein manage dein
" Required:
call dein#add('Shougo/dein.vim')

" Add or remove your plugins here:
call dein#add('Shougo/neosnippet.vim')
call dein#add('Shougo/neosnippet-snippets')

" You can specify revision/branch/tag.
call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

call dein#add('scrooloose/nerdtree')

" Golang
call dein#add('fatih/vim-go')

" js
call dein#add('pangloss/vim-javascript')

" Required:
call dein#end()

" Required:
filetype plugin indent on

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

"End dein Scripts-------------------------
