syntax on
set number
set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
set showmatch
set cursorline
set incsearch
set smarttab

set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'markonm/traces.vim'

call vundle#end()
filetype plugin indent on
