#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=$HOME/.nodebrew/current/bin:$PATH

autoload -Uz promptinit
promptinit
prompt steeef

alias vi=/usr/local/bin/vim
alias vim=vi

alias gst='git status'
alias gcm='git checkout master'
alias perf='gperf'

if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

export GOPATH=$HOME/work/go
